version: '3.8'

services:
  discord-mp3-bot:
    build: .
    container_name: discord-mp3-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    volumes:
      - ./downloads:/usr/src/app/downloads
